# this is yaml format (https://yaml.org/spec/1.2.2/)
# yaml space delimited, not tab, spaces must correct
# quick start guide here: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

# this must contain an entry for the month found in the reports it does not need historical info
exchange_rates:
    AUD to GBP:
      2023:
        June: 0.52  # conversion to GPB
        July: 0.52  # conversion to GPB
    CAD to GBP:
      2023:
        June: 0.58  # conversion to GPB
        July: 0.58  # conversion to GPB
    USD to GBP:
      2023:
        June: 0.76  # conversion to GPB
        July: 0.76  # conversion to GPB
    
# mps to finance cost mappings - finance categories must be a list
mps_category_mapping:
  Travel and Subsistence:                 # MPS category
    - 'accomodation'                        # Finance categories
    - 'accommodation'
    - 'airfares'
    - 'air fares'
    - 'car hire'
    - 'subsistence'
    - 'subsistance'
    - 'telephone'
    - 'travel'
  Aviation:                               # MPS category
     - 'aviation'                           # Finance categories
  Shipping:                               # MPS category
    - 'shipping'                            # Finance categories
  IS:                                     # MPS category
    - 'project is'                          # Finance categories
  Professional Services:
    - 'professional services'               # Finance categories
  Other:                                  # MPS category
    - 'equipment'
    - 'staff entertainment'
    - 'bank charges'
    - 'state tax deductions'
  Subcontractors:                         # MPS category
    - 'sub-contractors'                     # Finance categories
  Salaries - Ops:                         # MPS category
    - 'salaries - field ops'                # Finance categories
  Salaries - Production:                  # MPS category
    - 'salaries - production'               # Finance categories
  Salaries - Project Management:          # MPS category
     - 'salaries - project management'      # Finance categories
  Liquidated damages:                     # MPS category
     - 'liquidated damages'                 # Finance categories
  Cost of Goods Sold:                     # MPS category
    - 'total cost of sales'                 # Finance categories
    - 'total cost of goods sold'
  Internal Trade:                         # these categories are excluded
    - 'data processing'                     # Finance categories
    - 'data processing (internal)'
    - 'salaries internal trade'
    - 'sales - intercompany trading'
  Income:                                 # MPS category
    - 'services'                            # Finance categories
