#this is yaml format (https://yaml.org/spec/1.2.2/)
#yaml space delimited, not tab, spaces must correct
#quick start guide here: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

# this must contain an entry for the month found in the reports it does not need historical info
exchange_rates:
    AUD to GBP:
      2023:
        June: 0.531971  # conversion to GPB
        July: 0.53166  # conversion to GPB
    CAD to GBP:
      2023:
        June: 0.592838  # conversion to GPB
        July: 0.59598  # conversion to GPB
    USD to GBP:
      2023:
        June: 0.869943  # conversion to GPB
        July: 0.791703  # conversion to GPB
    
# mps to finance cost mappings - finance categories must be a list
# mps to finance cost mappings
mps_category_mapping:
  'Accommodation':                          # MPS category
    - 'accomodation'                        # Finance categories
    - 'accommodation'
  'Air Fares':                              # MPS category
    - 'airfares'                            # Finance categories
    - 'air fares'
  'Equipment':                              # MPS category
    - 'equipment'                           # Finance categories   
  'Aviation':                               # MPS category
    - 'aviation'                            # Finance categories
  'Professional Services':                  # MPS category    
    - 'professional services'               # Finance categories
  'Shipping':                               # MPS category
    - 'shipping'                            # Finance categories
  'Subsistence':                            # MPS category
    - 'subsistence'                         # Finance categories
    - 'subsistance'
  'Travel':                                 # MPS category
    - 'car hire'                            # Finance categories
    - 'travel'
  'Other':                                  # MPS category
    - 'staff entertainment'                 # Finance categories
    - 'bank charges'
    - 'state tax deductions'
    - 'safety clothing'
    - 'telephone'
    - 'project is'   
    - 'training'    
  'Subcontractors':                         # MPS category
    - 'sub-contractors'                     # Finance categories
  'Salaries - Ops':                         # MPS category
    - 'salaries - field ops'                # Finance categories
  'Salaries - Production':                  # MPS category
    - 'salaries - production'               # Finance categories
  'Salaries - Project Management':          # MPS category
    - 'salaries - project management'       # Finance categories
  'Liquidated damages':                     # MPS category
    - 'liquidated damages'                  # Finance categories
  'Cost of Goods Sold':                     # MPS category
    - 'total cost of sales'                 # Finance categories
    - 'total cost of goods sold'
  'Internal Trade':                         # these categories are ignored
    - 'data processing'                     # Finance categories
    - 'data processing (internal)'
    - 'salaries internal trade'
    - 'sales - intercompany trading'
  'Income':                                 # MPS category
    - 'services'                            # Finance categories
